repositories:
  - name: cert-manager
    url: https://charts.jetstack.io
  - name: minio
    url: https://charts.min.io

releases:
  - name: cert-manager
    namespace: cert-manager
    createNamespace: true
    chart: jetstack/cert-manager
    version: v1.12.0
    set:
      - name: installCRDs
        value: true

  - name: kserve-crd
    namespace: kserve
    createNamespace: true
    chart: oci://ghcr.io/kserve/charts/kserve-crd
    version: v0.13.0

  - name: kserve
    needs:
      - cert-manager/cert-manager
      - kserve-crd
    namespace: kserve
    chart: oci://ghcr.io/kserve/charts/kserve
    version: v0.13.0

  - name: minio
    namespace: mlflow
    createNamespace: true
    chart: minio/minio
    values:
      - buckets:
          - name: mlflow
            policy: public
            purge: false
        rootUser: minioadmin
        rootPassword: minioadmin
        mode: standalone
        replicas: 1
        extraEnv:
          MINIO_BROWSER: on
        resources:
          requests:
            memory: 2Gi
          limits:
            memory: 4Gi

  - name: postgres
    namespace: mlflow
    createNamespace: true
    chart: oci://registry-1.docker.io/bitnamicharts/postgresql
    version: 16.0.4
    values:
      - architecture: standalone
        service.ports.postgresql: 5432
        auth:
          postgresPassword: postgres
          database: mlflow
          username: mlflow
          password: mlflow

  - name: mlflow
    needs:
      - minio
      - postgres
    namespace: mlflow
    chart: oci://registry-1.docker.io/bitnamicharts/mlflow
    version: 2.0.2
    values:
      - minio.enabled: false
        postgresql.enabled: false
        externalDatabase:
          dialectDriver: postgresql
          host: postgres-postgresql
          port: 5432
          database: mlflow
          user: mlflow
          password: mlflow
        externalS3:
          host: minio-service
          port: 9000
          bucket: mlflow
          accessKeyId: minioadmin
          accessKeySecret: minioadmin