---
apiVersion: v1
kind: Secret
metadata:
  name: s3-inference-secret
  namespace: mlflow
  annotations:
    serving.kserve.io/s3-endpoint: mlflow-minio
    serving.kserve.io/s3-usehttps: "0"
    serving.kserve.io/s3-region: "us-east-2"
    serving.kserve.io/s3-useanoncredential: "true"
type: Opaque
stringData: # use `stringData` for raw credential string or `data` for base64 encoded string
  AWS_ACCESS_KEY_ID: YWRtaW4=
  AWS_SECRET_ACCESS_KEY: cGFzc3dvcmQK=
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: s3-inference-sa
  namespace: mlflow
secrets:
  - name: s3-inference-secret
---
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: "{replaced with MLflow Project name}"
  namespace: "{replaced with namespace}"
spec:
  predictor:
    serviceAccountName: s3-inference-sa
    model:
      modelFormat:
        name: mlflow
      protocolVersion: v2
      storageUri: "{replaced with URI of MLflow model}"
