apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ job_name }}"
  namespace: "{{ namespace }}"
spec:
  ttlSecondsAfterFinished: 100
  backoffLimit: 0
  template:
    spec:
      containers:
        - name: mlflow-project-runner
          image: "{{ image }}"
          env:
            - name: MLFLOW_TRACKING_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mlflow-tracking
                  key: admin-user
            - name: MLFLOW_TRACKING_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mlflow-tracking
                  key: admin-password
          resources:
            limits:
              cpu: 8
              memory: 8Gi
            requests:
              cpu: 2
              memory: 2Gi
      restartPolicy: Never
