---
apiVersion: v1
kind: Secret
metadata:
  name: s3-inference-secret
  namespace: mlflow
  annotations:
    serving.kserve.io/s3-endpoint: mlflow-minio
    serving.kserve.io/s3-usehttps: "0"
    serving.kserve.io/s3-region: "us-east-2"
    serving.kserve.io/s3-useanoncredential: "true"
type: Opaque
stringData: # use `stringData` for raw credential string or `data` for base64 encoded string
  AWS_ACCESS_KEY_ID: YWRtaW4=
  AWS_SECRET_ACCESS_KEY: cGFzc3dvcmQK=
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: s3-inference-sa
  namespace: mlflow
secrets:
  - name: s3-inference-secret
---
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: multilingual-e5-large
  namespace: mlflow
spec:
  predictor:
    serviceAccountName: s3-inference-sa
    containers:
      - name: kserve-container
        image: 326takeda/kserve-sentence-transformer:latest
        env:
          - name: STORAGE_URI
            value: s3://mlflow/3/c3dce6c6bcc245c2b7dd37924bb958e0/artifacts/multilingual-e5-large
          - name: APP_ARGS
            value: "--model_name multilingual-e5-large --predictor_protocol v2"